### PR TITLE
Campaign-clarifying priority points

### LINKED ISSUE #111: Campaign Game Make Priority Points More Clear
The main problem with the current design is that if the user only has one priority point available, they might try to add more than one priority point to some service and see that it does not work. We need a way to show the user exactly how much they can add. Here are some suggestions:
- Reinstate an explicit points thing
- **Color the buttons or X’s so that you can see they’re disabled**
- Explicit instructions e.g., “You can have 2 high priority, 3 medium, 5 low”
- Sequencing priorities into "buckets" of low, medium, and high priority.

### PR DESCRIPTION
**Pull request by JusticeV452**
- Changed the number of priority buttons to 3
- Fixed "i am not satisfied on " issue
- Changed the default priority of all categories to "low"
- Changed region color on results screen to be green at 50% to match result percent

### CODE REVIEW

File: frontend/src/campaign/speech.js [hunk 1]
```diff
@@ -126,23 +127,61 @@ export class Speech extends React.Component {
         }
     }
 
+    makeProposalDict(speech) {
```
Comment (ryaanahmed) [inline frontend/src/campaign/speech.js:130]: Looks good! Very clean change here -- great work.

File: frontend/src/campaign/speech.js [hunk 2]
```diff
@@ -126,23 +127,61 @@ export class Speech extends React.Component {
...
+    }
+
+    noProblem(dict) {
+        let acceptable = true;
+        let atMaxStatement = '';
+        for (const priority of Object.keys(this.max_priority_points)) {
+            if (dict[priority] > this.max_priority_points[priority]) {
+                acceptable = false;
+            } else {
+                atMaxStatement += 'You can have ' + (this.max_priority_points[priority]
```
Comment (ryaanahmed) [inline frontend/src/campaign/speech.js]: I'd suggest factoring the calculation out and using a template literal for ease of reading:

```
const priority_points_left = this.max_priority_points[priority] - dict[priority]
atMaxStatement += `You can have ${priority_points_left} more sectors at ${priority} priority.\n';
```

File: frontend/src/campaign/speech.js [hunk 3]
```diff
@@ -192,10 +228,10 @@ export class Speech extends React.Component {
                     {topic}
                 </div>
                 <div className='speech-option_btns'>
-                    {[...Array(5).keys()].map((score, j) => (
+                    {[...Array(3).keys()].map((score, j) => (
```
Comment (ryaanahmed) [inline frontend/src/campaign/speech.js]: I should've caught this in an earlier PR, but I'm noticing it now, so going to ask for change -- this kind of pattern is pretty hard to read, when it's doing something very simple (a map over [0,1,2]). My preference would be to make a React fragment inside of a normal for loop earlier in the render call.

`{[...Array(3).keys()].map((score, j) => (` technically works but it's pretty inscrutable! Plus `score` and `j` are totally redundant. Even `[0,1,2].map((score) =>` is clearer.

File: frontend/src/campaign/speech.js [hunk 4]
```diff
@@ -179,10 +218,7 @@ export class Speech extends React.Component {
     };
 
     priorityPoint() {
```
Comment (ryaanahmed) [inline frontend/src/campaign/speech.js]: Since this is just returning a value from the state dict, can we remove the function call and just put the value directly where it's being called?

**Review by ryaanahmed — CHANGES_REQUESTED** [review]
Really nice, clean refactor to the new functionality. I've got some style comments within to cleanup before we merge, but the basic design is right on course.
